- app/src/main/java/com/example/harumub_front/LoginActivity.kt
- app/src/main/java/com/example/harumub_front/MainActivity2.kt
- app/src/main/java/com/example/harumub_front/RecommendAdapter2.kt
- app/src/main/java/com/example/harumub_front/RetrofitClass.kt
- app/src/main/res/layout/movie_collection_layout.xml
- movie_collection_layout
- 유사 사용자 추천 콜렉션 클릭 시 유사 사용자 추천 리스트로 이동하도록 수정
- RecommendAdapter2
- 유사 사용자 추천 콜렉션 클릭 시 유사 사용자 추천 리스트로 이동하도록 수정
- RetrofitClass
- 선호 배우 추천 정보 데이터 추가
- 선호 배우 추천 정보 MainActivity2로 전달
- MainActivity2
- 메인 페이지에서 선호 배우 추천 목록 보여 주도록 수정
> 유사 사용자 추천 콜렉션 클릭 시 유사 사용자 추천 목록으로 이동 & 선호 배우 추천 목록 보여 주기

- app/src/main/res/layout/fragment_user_movie_list.xml
- fragment_user_movie_list
- 드로어 메뉴 id 변경
> 유사 사용자 추천 목록 오류 수정

- app/src/main/java/com/example/harumub_front/LoginActivity.kt
> 로그인 로딩창 수정

- app/src/main/java/com/example/harumub_front/AddreviewActivity.kt
- app/src/main/java/com/example/harumub_front/LoginActivity.kt
- app/src/main/java/com/example/harumub_front/MainActivity2.kt
- app/src/main/java/com/example/harumub_front/ResultActivity.kt
- app/src/main/java/com/example/harumub_front/SearchActivity.kt
- app/src/main/java/com/example/harumub_front/SignupActivity.kt
- app/src/main/java/com/example/harumub_front/UserMovieListActivity.kt
- app/src/main/java/com/example/harumub_front/WatchAloneActivity.kt
- app/src/main/java/com/example/harumub_front/WatchListActivity.kt
- AddreviewActivity
- 오류 Toast Message 주석 처리
- 오류 Toast Message 주석 처리
- MainActivity2
- 오류 Toast Message 주석 처리
- ResultActivity
- 오류 Toast Message 주석 처리
- SearchActivity
- 오류 Toast Message 주석 처리
- SignupActivity
- 오류 Toast Message 주석 처리
- email code 다르게 입력했을 때의 Toast Message는 제외
- UserMovieListActivity
- 오류 Toast Message 주석 처리
- 오류 Toast Message 주석 처리
- WatchListActivity
- 오류 Toast Message 주석 처리
> 페이지별 오류 Toast Message 주석 처리

- app/src/main/java/com/example/harumub_front/LoginActivity.kt
- app/src/main/java/com/example/harumub_front/MainActivity2.kt
- app/src/main/java/com/example/harumub_front/RecommendAdapter4.kt
- app/src/main/java/com/example/harumub_front/RecommendAdapter5.kt
- app/src/main/java/com/example/harumub_front/RecommendAdapter6.kt
- app/src/main/java/com/example/harumub_front/RetrofitClass.kt
- app/src/main/res/layout/activity_main2.xml
- activity_main2
- 메인 페이지 UI 수정(고전 TOP 10 목록, 연도별 영화 추천 목록, 리메이크 작품 추천 목록 추가)
- 로그인 시 추천 데이터 받아오도록 수정
- 로그인 시 받은 추천 데이터 메인 페이지로 전달
- MainActivity2
- 로그인 페이지로부터 추천 데이터 받아오도록 수정
- 추천 데이터를 화면에 띄우도록 RecyclerView와 Adapter 연결
- 추천 데이터 다른 페이지로 전달
- RetrofitClass
- 연도별 영화 추천 데이터 추가
- 리메이크 작품 추천 데이터 추가
- 고전 TOP 10 데이터 추가
- RecommendAdapter4
- 연도별 영화 추천 목록 RecyclerView와 연결해 줄 Adapter
- RecommendAdapter5
- 리메이크 작품 추천 목록 RecyclerView와 연결해 줄 Adapter
- RecommendAdapter6
- 고전 TOP 10 목록 RecyclerView와 연결해 줄 Adapter
> 메인 페이지에 고전 TOP 10 목록, 연도별 영화 추천 목록, 리메이크 작품 추천 목록 추가

- app/src/main/java/com/example/harumub_front/MainActivity2.kt
- MainActivity2
- 메인 페이지 RecyclerView와 Adapter 연결 수정
> 메인 페이지 RecyclerView 수정

- app/src/main/java/com/example/harumub_front/RetrofitInterface.kt
- app/src/main/java/com/example/harumub_front/WatchAloneActivity.kt
- RetrofitInterface
- 장면 분석
- 영화 검색 페이지에서 선택한 영화 재생 - 주석으로 작성
- 혼자보기 영화 감상 종료 시 장면 분석 호출
> 영화 검색 페이지에서 선택한 영화 재생(주석으로 작성) & 혼자보기 영화 감상 종료 시 장면 분석 호출

- app/src/main/java/com/example/harumub_front/ResultActivity_ticket_back.kt
- local.properties
- ResultActivity_ticket_back
- 리메이크 작품 추천 다이얼로그 크기 설정
> 리메이크 작품 추천 다이얼로그 크기 설정

- app/src/main/java/com/example/harumub_front/WatchAloneActivity.kt
> 혼자보기 영화 감상 시작했을 경우 뒤로 가기 막기

- app/src/main/java/com/example/harumub_front/WatchAloneActivity.kt
- 혼자보기 영화 감상 종료 후 분석 시 화면 켜짐 유지
> 혼자보기 영화 감상 종료 후 분석 시 화면 켜짐 유지

- app/src/main/java/com/example/harumub_front/TogetherActivity.kt
- app/src/main/res/layout/activity_watch_together.xml
- TogetherActivity
- 같이보기 종료 시 입장 페이지로 추천 데이터 전달 수정
- activity_watch_together
- tools:context 수정
> 같이보기 종료 시 입장 페이지로 추천 데이터 전달 수정

- app/src/main/java/com/example/harumub_front/WatchAloneActivity.kt
- 홈 버튼 이벤트 수정
- 혼자보기 영화 감상 도중 홈 버튼 감지 시 화면 켜짐 유지
- 다이얼로그 '확인' 버튼 클릭 후 로딩 화면 띄우기
- 다이얼로그 '확인' 버튼 클릭 후 장면 분석 호출
> 혼자보기 영화 감상 도중 홈 버튼 감지 이벤트 수정

- app/src/main/java/com/example/harumub_front/WatchAloneActivity.kt
- app/src/main/res/layout/activity_watch_alone.xml
- 혼자보기 영화 화면 비율 조정
- activity_watch_alone
- 혼자보기 영화 화면 비율 조정
> 혼자보기 영화 화면 비율 조정

- app/src/main/java/com/example/harumub_front/WatchAloneActivity.kt
- local.properties
- 자고 있을 경우 이벤트 수정
- 혼자보기 영화 감상 도중 자고 있을 경우 화면 켜짐 유지
- 다이얼로그 '확인' 버튼 클릭 후 로딩 화면 띄우기
- 다이얼로그 '확인' 버튼 클릭 후 장면 분석 호출
> 혼자보기 영화 감상 도중 자고 있을 경우 이벤트 수정

- app/src/main/java/com/example/harumub_front/LoginActivity.kt
- local.properties
- 로그인 성공 시 다이얼로그에서 Toast Message로 변경
> 로그인 성공 시 Toast Message

- app/src/main/java/com/example/harumub_front/LoginActivity.kt
- app/src/main/res/layout/activity_watch_alone.xml
- 로그인 성공 다이얼로그 수정(중복 삭제)
- 혼자보기 '시작' 버튼 이름 '재생'으로 변경
> 로그인 성공 다이얼로그 수정 & 혼자보기 시작 버튼 이름 변경

- app/src/main/java/com/example/harumub_front/AddreviewActivity.kt
- app/src/main/java/com/example/harumub_front/ResultActivity_ticket_front.kt
- app/src/main/java/com/example/harumub_front/WatchAloneActivity.kt
- app/src/main/java/com/example/harumub_front/WatchListAdapter.kt
- AddreviewActivity
- 혼자보기 감상을 했을 경우 감상 결과 티켓 앞 페이지에서 뒤로 가기 막기
- ResultActivity_ticket_front
- 혼자보기 감상을 했을 경우 감상 결과 티켓 앞 페이지에서 뒤로 가기 막기
- 혼자보기 감상을 했을 경우 감상 결과 티켓 앞 페이지에서 뒤로 가기 막기
- WatchListAdapter
- 혼자보기 감상을 했을 경우 감상 결과 티켓 앞 페이지에서 뒤로 가기 막기
> 혼자보기 감상을 했을 경우 감상 결과 티켓 앞 페이지에서 뒤로 가기 막기

- app/src/main/java/com/example/harumub_front/EnterActivity.kt
- app/src/main/java/com/example/harumub_front/TogetherActivity.kt
- EnterActivity
- '초대코드 입장' 버튼 클릭 시 나타나는 다이얼로그의 '네' 버튼 클릭 시 다이얼로그 닫기
- TogetherActivity
- 주석 삭제
> '초대코드 입장' 버튼 클릭 시 나타나는 다이얼로그의 '네' 버튼 클릭 시 다이얼로그 닫기

- app/src/main/java/com/example/harumub_front/MainActivity.kt
- app/src/main/java/com/example/harumub_front/WatchAloneActivity.kt
- app/src/main/res/layout/activity_main.xml
- MainActivity
- 뒤로 가기 버튼 두 번 클릭 시 로그아웃
- activity_main
- 뒤로 가기 버튼 두 번 클릭 시 로그아웃
- 영화 검색 페이지에서 선택한 영화 재생 - 주석 삭제
> 뒤로 가기 버튼 두 번 클릭 시 로그아웃 & 영화 검색 페이지에서 선택한 영화 재생 - 주석 삭제

- app/src/main/java/com/example/harumub_front/ResultActivity_ticket_front.kt
- app/src/main/java/com/example/harumub_front/WatchAloneActivity.kt
- ResultActivity_ticket_front
- 감상 결과 페이지에서 뒤로 가기 버튼 이벤트 주석 처리
- 혼자보기 페이지에서 뒤로 가기 버튼 이벤트 주석 처리
> 혼자보기 페이지와 감상 결과 페이지에서 뒤로 가기 버튼 이벤트 주석 처리
